[assign]

[relabel]
allow-unauthenticated = [
    "-Z*",
    "A-*",
    "C-*",
    "D-*",
    "E-*",
    "F-*",
    "I-*",
    "L-*",
    "O-*",
    "PG-*",
    "S-*",
    "T-*",
    "WG-*",
    "needs-triage",
]

[no-mentions]

[canonicalize-issue-links]

# Automatically close and reopen PRs made by bots to run CI on them
[bot-pull-requests]

[behind-upstream]
days-threshold = 7
