name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust (for mdBook)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdBook
        run: |
          cargo install mdbook
          cargo install mdbook-toc
          cargo install mdbook-mermaid
          cargo install mdbook-linkcheck2

      - name: Set executable permissions for linkcheck
        run: chmod +x ci/linkcheck.sh

      - name: Set executable permissions for check-in
        run: chmod +x ci/check-in.sh

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./book
